spring.profiles.active=depot
spring.main.web-environment=false

obtu.log.folder=${basedir}/log
obtu.log.filename=vdt
obtu.log.filename.suffix=log

lcm.rest.api.protocol=http
lcm.rest.api.host=127.0.0.1
lcm.rest.api.port=7400

################### Depot Properties ########################
lcm.depot.adapter.host=dl.broadcom.com
lcm.depot.adapter.certificateCheckEnabled=true
lcm.depot.adapter.enableBundleSignatureValidation=true
lcm.depot.adapter.enableSignatureValidation=true
lcm.depot.adapter.remote.v2.rootDir=/PROD
lcm.depot.adapter.remote.repoDir=/COMP/SDDC_MANAGER_VCF
lcm.depot.adapter.remote.index.filename=index.v3
lcm.depot.adapter.remote.productVersionCatalog.filename=productVersionCatalog.json
lcm.depot.adapter.remote.lcmManifestDir=/COMP/SDDC_MANAGER_VCF/lcm/manifest
lcm.depot.adapter.remote.offline.index.filename=index.offline
lcm.depot.adapter.local.baseDir=${lcm.bundle.download.root.dir}/tmpRootDir
lcm.depot.adapter.local.input.spec.dirname=asyncPatchSpecs
lcm.depot.adapter.local.compatibility.path=v1/products/bundles/type/vcf-lcm-bundle
lcm.depot.adapter.lcmManifestFile=lcmManifest.json
lcm.depot.adapter.vcfManifestFile=vcfManifest.json
lcm.depot.adapter.remote.vcfMetadataDir=/metadata
lcm.depot.adapter.remote.vcfManifestDir=/manifest
lcm.depot.adapter.remote.vcfBinariesDir=/COMP
lcm.bundle.download.root.dir=${user.home}
lcm.bundle.download.default.dir=${lcm.bundle.download.root.dir}/PROD/COMP/SDDC_MANAGER_VCF
lcm.manifest.download.default.dir=lcm/manifest
lcm.bundle.manifest.dirname=manifests
lcm.bundle.dirname=bundles
lcm.depot.download.tool.name=vcf-download-tool

################### Compatibility Data Properties ###################
vcf.compatibility.controllers.vvs.api.clientId=vcf-tools
vcf.compatibility.controllers.vvs.api.memorySize=16777216
vcf.compatibility.controllers.maxRetries=6
vcf.compatibility.controllers.backOffPeriod=7
vcf.compatibility.controllers.vvs.api.endpoint=vvs.broadcom.com
vcf.compatibility.controllers.vvs.api.path=v1/products/bundles/type/vcf-lcm-v2-bundle
vcf.compatibility.controllers.vvs.api.unifiedPath=v1/products/bundles/type/vcf-interop-bundle
vcf.compatibility.controllers.vvs.api.vlcmBundlePath=v1/products/bundles/vlcm-compatibility-data/v1/vlcm-interop-vcg-bundle

################### HCL download properties ###################
vsan.hcl.client.endpoint=vsanhealth.vmware.com
vsan.hcl.client.clientId=VCF-B1B0D465-4D2D-4AE9-9A34-C335C81218B5-SEP-2024
vsan.hcl.client.protocol=https
vsan.hcl.client.port=443
vsan.hcl.client.connect.timeout=120
vsan.hcl.client.socket.timeout=120

################# LabFoundry defaults #################
binaries.download.skip.metadata.download=false
lcm.depot.adapter.enableBundleChecksumValidation=true
enable.binary.post.processing=true
feature.vcf.watermarking=true
