#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import json
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]


def run(command: list[str], cwd: Path = ROOT) -> subprocess.CompletedProcess[str]:
    return subprocess.run(command, cwd=cwd, check=False, capture_output=True, text=True)


def git_value(args: list[str]) -> str:
    result = run(["git", *args])
    if result.returncode != 0:
        raise SystemExit(result.stderr.strip() or f"git {' '.join(args)} failed")
    return result.stdout.strip()


def project_version(pyproject_text: str) -> str:
    match = re.search(r'^version\s*=\s*"([^"]+)"', pyproject_text, flags=re.MULTILINE)
    if not match:
        raise SystemExit("pyproject.toml does not define [project] version")
    return match.group(1)


def version_with_git(base_version: str, git_commit: str) -> str:
    base = base_version.split("+", 1)[0]
    short = re.sub(r"[^0-9A-Fa-f]", "", git_commit)[:12]
    return f"{base}+g{short}" if short else base


def copy_source(target: Path) -> None:
    ignore = shutil.ignore_patterns(
        ".git",
        ".venv",
        ".pytest_cache",
        "build",
        "data",
        "dist",
        "output",
        "ovf",
        "test-results",
        "test-vms",
        "__pycache__",
        "*.pyc",
    )
    shutil.copytree(ROOT, target, ignore=ignore)


def patch_version(source: Path, version: str, git_commit: str, built_at: str) -> None:
    pyproject = source / "pyproject.toml"
    text = pyproject.read_text(encoding="utf-8")
    text = re.sub(r'(^version\s*=\s*")[^"]+(")', rf"\g<1>{version}\2", text, count=1, flags=re.MULTILINE)
    pyproject.write_text(text, encoding="utf-8")
    build_py = source / "labfoundry" / "_build.py"
    build_py.write_text(
        "\n".join(
            [
                '"""Build metadata generated by scripts/build_update_wheel.py."""',
                f'BUILD_VERSION = "{version}"',
                f'GIT_COMMIT = "{git_commit}"',
                f'BUILD_TIME_UTC = "{built_at}"',
                "",
            ]
        ),
        encoding="utf-8",
    )


def build_wheel(source: Path, dist: Path) -> Path:
    dist.mkdir(parents=True, exist_ok=True)
    result = run([sys.executable, "-m", "pip", "wheel", "--no-deps", str(source), "-w", str(dist)], cwd=source)
    if result.returncode != 0:
        raise SystemExit((result.stdout + "\n" + result.stderr).strip())
    wheels = sorted(dist.glob("labfoundry-*.whl"), key=lambda path: path.stat().st_mtime, reverse=True)
    if not wheels:
        raise SystemExit("wheel build completed but no labfoundry wheel was found")
    return wheels[0]


def main() -> int:
    parser = argparse.ArgumentParser(description="Build a repository-style LabFoundry update wheel and channel manifests.")
    parser.add_argument("-o", "--output", default="dist/update", help="Repository output directory.")
    parser.add_argument("--channel", choices=("stable", "preview", "development"), default="stable", help="Release channel to update.")
    parser.add_argument("--clean", action="store_true", help="Remove the existing repository tree before publishing this channel.")
    args = parser.parse_args()

    pyproject_text = (ROOT / "pyproject.toml").read_text(encoding="utf-8")
    git_commit = git_value(["rev-parse", "HEAD"])
    built_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat().replace("+00:00", "Z")
    version = version_with_git(project_version(pyproject_text), git_commit)
    output = (ROOT / args.output).resolve()
    if output.exists() and args.clean:
        shutil.rmtree(output)
    output.mkdir(parents=True, exist_ok=True)

    with tempfile.TemporaryDirectory(prefix="labfoundry-update-build-") as temp_root:
        temp_path = Path(temp_root)
        source = Path(temp_root) / "src"
        copy_source(source)
        patch_version(source, version, git_commit, built_at)
        built_wheel = build_wheel(source, temp_path / "wheel")
        packages = output / "packages"
        packages.mkdir(parents=True, exist_ok=True)
        wheel = packages / built_wheel.name
        shutil.copy2(built_wheel, wheel)

    digest = hashlib.sha256(wheel.read_bytes()).hexdigest()
    manifest = {
        "schema_version": 1,
        "name": "labfoundry",
        "version": version,
        "git_commit": git_commit,
        "built_at": built_at,
        "requires_python": ">=3.12",
        "wheel": f"../../packages/{wheel.name}",
        "sha256": digest,
    }
    channel_dir = output / "channels" / args.channel
    channel_dir.mkdir(parents=True, exist_ok=True)
    channel_manifest = channel_dir / "manifest.json"
    channel_manifest.write_text(json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    compatibility_manifest = {**manifest, "wheel": f"packages/{wheel.name}"}
    (output / "manifest.json").write_text(json.dumps(compatibility_manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    index_path = output / "index.json"
    try:
        existing_index = json.loads(index_path.read_text(encoding="utf-8")) if index_path.exists() else {}
    except json.JSONDecodeError:
        existing_index = {}
    channels = existing_index.get("channels") if isinstance(existing_index, dict) else {}
    channels = dict(channels) if isinstance(channels, dict) else {}
    channels[args.channel] = f"channels/{args.channel}/manifest.json"
    repository_index = {
        "schema_version": 1,
        "name": "labfoundry",
        "channels": dict(sorted(channels.items())),
        "generated_at": built_at,
    }
    index_path.write_text(json.dumps(repository_index, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(f"built {wheel}")
    print(f"channel manifest {channel_manifest}")
    print(f"repository index {index_path}")
    print(f"compatibility manifest {output / 'manifest.json'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
